name: sportapplication
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  get: ^4.6.5
  shared_preferences: ^2.2.2
  image_picker: ^0.8.4+5
  image_cropper: ^4.0.1
  cupertino_icons: ^1.0.6
  glassmorphism: ^3.0.0
  syncfusion_flutter_charts: 21.2.3
  youtube_player_flutter: ^8.1.2
  video_player: ^2.7.2
  easy_date_timeline: ^1.0.2
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/
  
  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
  


